### ISSUE TITLE
databinding fails for foundation switch while using the tour steptext 

### ISSUE THREAD

**Issue by asulaiman** [yalabot/angular-foundation#108]
When you add step text for a tour within the foundation switch, angular fails to bind switch data to its models on change. Try following fiddle - 

http://jsfiddle.net/r6gphz40/

**Comment by jbrowning** [comment]
Really not sure what you're trying to demonstrate with that fiddle. Can you please explain?

**Comment by asulaiman** [comment]
Like i said in the comment, adding a tour step text to the foundation switch breaks the databinding of the switch model.Click on the switch at the top and observe the resulting value coming from the switch. The value does not get bound to its model. Now try removing the step text from the switch directive and then click on the switch. The value is shown in the alert box.
